### ISSUE TITLE
Intelephense: method does not exist for models

### ISSUE THREAD

**Issue by ermand** [kauffinger/lazyvim#1]
Hello 👋🏻
First of all, thank you for this start for LazyVim + Laravel. I have used LazyVim for a while now but now I have to work on a Laravel project and checking on how to configure it. I came across your repo and really appreciate your sharing 😃

So far it is working mostly Ok for me, apart of the issue for `intelephense` not recognising some methods such as `Model::create`. I do have the license for `intelephense`.
I was wondering if you have this issue as well, and if YES, did you find a way to solve it?

Thank you in advance 😃

**Example**
<img width="738" alt="image" src="https://github.com/kauffinger/lazyvim/assets/2822729/8dc8b47c-eadc-4184-9ce1-18512cdd380b">

**Comment by kauffinger** [comment]
Great find, there is a lot of small things that are sometimes needed due to "Laravel Magic"
Do you mind sharing what version of Laravel you are on? I remember this being an issue once, but I have not encountered it with our current projects - I suspect newer versions of Laravel have addressed this.

Thanks for bringing it to my attention, I will put a note in the README :)

**Comment by ermand** [comment]
Yes, you are totally right, it's working OK with newer versions of Laravel +10. The project that I currently jumped into is in Laravel 8 and it looks like it was needed there to have the `laravel-id-helper` package installed 😃
