### ISSUE TITLE
Blade TreeSitter Highlighting

### ISSUE THREAD

**Issue by kauffinger** [kauffinger/lazyvim#8]
Something is still going wrong - it seems to work generally (looking at `:InspectTree`), but the custom queries/highlights/injections don't.

I'm looking for someone more experienced while I fiddle around.

**Comment by kauffinger** [comment]
Improved a lot in [94a2d3e](https://github.com/kauffinger/lazyvim/commit/94a2d3eef1bc70e7a032872731af325f4b828fae)

**Comment by pinsard** [comment]
Hi, Kauffinger,

I just found your configs (because I have decided to adopt Neovim as my base tool, thanks to Jess Archer suggestion and explanations about what differentiate Neovim from vim) and, in the process of installing your configs I found a problem (unrelated to this thread), came here in search for directions, and noticed you're also seeking for some help.

Well, not sure what you mean by "more experienced" but I'm willing to bite the bullet (not to the extreme meaning of it, of course) and collaborate. I really find your intent of making Laravel work as fine in Neovim, and extending this to help others in the process, something to positive, so I wanna jump in. Please, find me in Telegram, @pinsard. Let's do this.
